name: test and release
on:
  push:
    branches:
      - '**'
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    #- name: Get dependencies
    #  run: go get -v -t -d ./...

    - name: Test code
      run: go test -v .

    - name: Slack notification
      if: failure()  # success()
      uses: rtCamp/action-slack-notify@v2.0.2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: athena-cli
        SLACK_ICON_EMOJI: ':woman-gesturing-no:'
        SLACK_TITLE: test failure
        SLACK_COLOR: danger # good
        SLACK_CHANNEL: api-test

  release:
    if: startsWith(github.ref, 'refs/tags/v') # && endsWith(github.ref, '-foobar')
    runs-on: ${{ matrix.os }}
    needs: test

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # https://github.com/actions/checkout
        with:
          fetch-depth: 0

      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
           go-version: 1.16

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
          workdir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
